apiVersion: v1
kind: Pod
metadata:
  annotations:
    gatekeeper.sh/mutation-id: 960fc211-eb6b-462d-987b-9f193edaecd0
    gatekeeper.sh/mutations: Assign//containers-drop-all-capabilities:1, Assign//default-fs-group:1,
      Assign//default-seccomp-profile:1, Assign//deny-privilege-escalation:1, Assign//run-as-non-root:2,
      AssignMetadata//annotate-seccomp-pod-runtime:1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"nginx","namespace":"starter-pack-0"},"spec":{"containers":[{"image":"nginxinc/nginx-unprivileged:latest","name":"nginx","ports":[{"containerPort":80}],"securityContext":{"allowPrivilegeEscalation":false}}],"securityContext":{"supplementalGroups":[2]}}}
    kubernetes.io/psp: restricted
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2023-09-20T11:00:11Z"
  name: nginx
  namespace: starter-pack-0
  resourceVersion: "87505"
  uid: 67c408de-26df-43d3-a1be-1b1d43c464bf
spec:
  containers:
  - image: nginxinc/nginx-unprivileged:latest
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tl8gz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-20-120-243.eu-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  priorityClassName: default
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups:
    - 2
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-tl8gz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-20T11:00:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-20T11:00:11Z"
    message: 'containers with unready status: [nginx]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-20T11:00:11Z"
    message: 'containers with unready status: [nginx]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-20T11:00:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: nginxinc/nginx-unprivileged:latest
    imageID: ""
    lastState: {}
    name: nginx
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.20.120.243
  phase: Pending
  qosClass: BestEffort
  startTime: "2023-09-20T11:00:11Z"
