apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"nginx","namespace":"starter-pack-0"},"spec":{"containers":[{"image":"nginxinc/nginx-unprivileged:latest","name":"nginx","ports":[{"containerPort":80}]}]}}
    kubernetes.io/psp: restricted
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2023-09-19T08:34:47Z"
  name: nginx
  namespace: starter-pack-0
  resourceVersion: "28140"
  uid: a739916b-0e74-436b-9777-357bcf59ad41
spec:
  containers:
  - image: nginxinc/nginx-unprivileged:latest
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wwcwj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-20-48-24.eu-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  priorityClassName: default
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups:
    - 1
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-wwcwj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-19T08:34:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-19T08:34:49Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-19T08:34:49Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-19T08:34:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://10a5ab43c2486824f988dc71fb676d7474d1da7e2eeea9d7859a39b87ba496aa
    image: docker.io/nginxinc/nginx-unprivileged:latest
    imageID: docker.io/nginxinc/nginx-unprivileged@sha256:be4590dc897a62c4ae2d388604d88afb6d139e24202611a200c9f29d137c173d
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-09-19T08:34:49Z"
  hostIP: 172.20.48.24
  phase: Running
  podIP: 172.20.32.128
  podIPs:
  - ip: 172.20.32.128
  qosClass: BestEffort
  startTime: "2023-09-19T08:34:47Z"
