apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-test-2
  namespace: starter-pack-0
  labels:
    app: test
    owner: cloud-platform
    env: dev
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: test
        owner: cloud-platform
        env: dev
    spec: 
      containers:
      - name: test
        image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:  
          limits:  
            cpu: 200m  
            memory: 20Mi  
          requests:  
            cpu: 100m  
            memory: 10Mi  
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
      - name: tmp
        emptyDir: {}
      initContainers:
      - name: init-test-2-init
        image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Hello, Init Nginx!" > /tmp/init_index.html']
