apiVersion: v1
kind: Pod
metadata:
  name: init-test-5
  namespace: starter-pack-0
  labels:
    app: test
    owner: cloud-platform
    env: dev
spec:
  containers:
    - name: test
      image: nginxinc/nginx-unprivileged:latest
      imagePullPolicy: IfNotPresent
      securityContext:  
        allowPrivilegeEscalation: true  
        runAsUser: 1000  
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        capabilities:
          drop: ["ALL"]  
        seccompProfile:
          type: "RuntimeDefault"
      ports:
      - containerPort: 8080
      resources:  
        limits:  
          cpu: 200m  
          memory: 20Mi  
        requests:  
          cpu: 100m  
          memory: 10Mi  
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  volumes:
  - name: tmp
    emptyDir: {}
  initContainers:
    - name: init-test-5-init
      image: nginxinc/nginx-unprivileged:latest
      imagePullPolicy: IfNotPresent
      securityContext:  
        allowPrivilegeEscalation: true  
        runAsUser: 1000  
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        capabilities:
          drop: ["ALL"]  
        seccompProfile:
          type: "RuntimeDefault"
      command: ['sh', '-c', 'echo "Hello, Init Nginx!" > /tmp/init_index.html']
      volumeMounts:
      - mountPath: /tmp
        name: tmp